### ISSUE TITLE
doesn't change files

### ISSUE THREAD

**Issue by gondo** [dg/composer-backslasher#2]
- bug report? yes
- feature request? no

### Description
after installing this package and running `composer update`, i can see the message "Composer Backslasher: Added 39 backslashes." but in reality no file has changed (i have nothing to commit)

### Steps To Reproduce
1. run `composer require dg/composer-backslasher`
2. git status:
```
	modified:   composer.json
	modified:   composer.lock
	modified:   symfony.lock
```
3. run `composer update`
4. see "Composer Backslasher: Added 39 backslashes."
5. git status:
```
	modified:   composer.json
	modified:   composer.lock
	modified:   symfony.lock
```
6. 🤔

**Comment by gondo** [comment]
ah i see.
it would be good to mention this in the README file.

**Comment by dg** [comment]
I agree, could you send PR to readme?

**Comment by gondo** [comment]
what about checking application files?
maybe by using some flag so it can be run only once as a onetime cleanup?

**Comment by dg** [comment]
In order to modify project is imho better to use different tool.
